##############################################################################
#
#   Kennedy Institute of Rheumatology
#
#   $Id$
#
#   Copyright (C) 2018 Stephen Sansom
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
###############################################################################

"""===========================
Pipeline Align
===========================

:Author: Sansom lab
:Release: $Id$
:Date: |today|
:Tags: Python

Overview
========

This pipeline performs alignments between samples using CCA (Seurat) and
Zinbwave.

Usage
=====

See :ref:`PipelineSettingUp` and :ref:`PipelineRunning` on general
information how to use CGAT pipelines.

Configuration
-------------

The pipeline requires a configured :file:`pipeline.yml` file.

Default configuration files can be generated by executing:

   python <srcdir>/pipeline_align.py config


Input files
-----------

The pipeline starts from a seurat object containing all of
the data which should be linked into the "data.dir" subfolder

e.g.

$ ls data.dir
combined_data.rds

A meta data column on which to partition the object for alignment
must be specified in the pipeline.yml file.


Dependencies
------------

This pipeline requires:

* cgat-core: https://github.com/cgat-developers/cgat-core
* R & various packages.


Pipeline output
===============

* A seurat object aligned with CCA
* A seurat object aligned with Zinbwave

"""

from ruffus import *
from pathlib import Path
import sys
import os
import shutil
import glob
import sqlite3
import numpy as np
import pandas as pd
from scipy.stats.mstats import gmean
import cgatcore.experiment as E
from cgatcore import pipeline as P
import cgatcore.iotools as IOTools

# -------------------------- < parse parameters > --------------------------- #

# load options from the config file
PARAMS = P.get_parameters(
    ["%s/pipeline.yml" % os.path.splitext(__file__)[0],
     "../pipeline.yml",
     "pipeline.yml"])

# set the location of the tenx code directory
if "tenx_dir" not in PARAMS.keys():
    PARAMS["tenx_dir"] = Path(__file__).parents[1]
else:
    raise ValueError("Could not set the location of the tenx code directory")


# ----------------------- < pipeline configuration > ------------------------ #

# handle pipeline configuration
if len(sys.argv) > 1:
        if(sys.argv[1] == "config") and __name__ == "__main__":
                    sys.exit(P.main(sys.argv))


# ########################################################################### #
# ############################### CCA Alignment ############################# #
# ########################################################################### #


@follows(mkdir("seurat.align.dir"))
@transform("data.dir/*.rds",
           regex(r".*/(.*).rds"),
           r"seurat.align.dir/\1.cca.sentinel")
def cca(infile, outfile):
    '''
       Perform the canonical correlation analysis
    '''

    job_memory = PARAMS["cca_memory"]

    outname = outfile.replace(".sentinel", ".rds")
    log_file = outfile.replace(".sentinel", ".log")

    statement = '''Rscript %(tenx_dir)s/R/seurat_cca.R
                   --seuratobject=%(infile)s
                   --metavar=%(align_metavar)s
                   --strata=%(align_strata)s
                   --niter=%(cca_niter)s
                   --numccs=%(cca_numccs)s
                   --outfile=%(outname)s
                   &> %(log_file)s
                '''

    P.run(statement)
    IOTools.touch_file(outfile)

@transform(cca,
           regex(r".*/(.*).cca.sentinel"),
           r"seurat.align.dir/\1.cca.plot.sentinel")
def ccaPlots(infile, outfile):
    '''
       Make biocor plots and component heatmaps
    '''

    job_memory = PARAMS["cca_memory"]

    infile = infile.replace(".sentinel", ".rds")
    outprefix = outfile.replace(".sentinel", "")
    log_file = outfile.replace(".sentinel", ".log")

    statement = '''Rscript %(tenx_dir)s/R/seurat_cca_plots.R
                   --seuratobject=%(infile)s
                   --metavar=%(align_metavar)s
                   --numccs=%(cca_numccs)s
                   --outprefix=%(outprefix)s
                   &> %(log_file)s
                '''

    P.run(statement)
    IOTools.touch_file(outfile)


@transform(cca,
           regex(r".*/(.*).cca.sentinel"),
           r"seurat.align.dir/\1.cca.aligned.sentinel")
def alignSubspace(infile, outfile):
    '''
       Align the subspace
    '''

    job_memory = PARAMS["cca_memory"]

    infile = infile.replace(".sentinel", ".rds")
    outname = outfile.replace(".sentinel", ".rds")
    log_file = outfile.replace(".sentinel", ".log")

    statement = '''Rscript %(tenx_dir)s/R/seurat_cca_align_subspace.R
                   --seuratobject=%(infile)s
                   --metavar=%(align_metavar)s
                   --dimsalign=%(cca_dimsalign)s
                   --outfile=%(outname)s
                   &> %(log_file)s
                '''

    P.run(statement)
    IOTools.touch_file(outfile)

@follows(ccaPlots, alignSubspace)
def runCCA():
    pass

# ########################################################################### #
# ################################## Zinbwave  ############################# #
# ########################################################################### #

@follows(mkdir("zinbwave.dir"))
@transform("data.dir/*.rds",
           regex(r".*/(.*).rds"),
           r"zinbwave.dir/\1.zinbwave.sentinel")
def zinbwave(infile, outfile):
    '''
       Compute reduced dimensions with zinbwave
    '''

    job_memory = PARAMS["zinbwave_memory"]
    job_threads = PARAMS["zinbwave_ncpu"]

    k_values = [x.strip() for x in str(PARAMS["zinbwave_k"]).split(",")]

    statements = []

    for k_value in k_values:

        outname = outfile.replace(".sentinel",
                                  ".k" + k_value + ".rds")

        log_file = outname.replace(".rds", ".log")

        stat = '''module unload apps/gsl;
                  Rscript %(tenx_dir)s/R/zinbwave.R
                       --seuratobject=%(infile)s
                       --metavar=%(align_metavar)s
                       --strata=%(align_strata)s
                       --K=%(k_value)s
                       --X=%(zinbwave_formula)s
                       --ncpu=%(zinbwave_ncpu)s
                       --ncells=%(zinbwave_ncells)s
                       --ngenes=%(zinbwave_ngenes)s
                       --backend=%(zinbwave_backend)s
                       --outfile=%(outname)s
                       &> %(log_file)s
                    ''' % {**locals(), **PARAMS}

        statements.append(stat)

    P.run(statements)

    IOTools.touch_file(outfile)


# ########################################################################### #
# ##################### full target: to run all tasks ####################### #
# ########################################################################### #

@follows(runCCA, zinbwave)
def full():
    pass


# ------------------- < ***** end of pipeline **** > ------------------------ #

if __name__ == "__main__":
    sys.exit(P.main(sys.argv))
