
#' A function to generate alluvial plots for two cluster resolutions
#' @param path_clusters_left A rds file with cluster assignments for each cell (as generated by seurat pipeline), to be plotted on the left side
#' @param path_clusters_right A rds file with cluster assignments for each cell (as generated by seurat pipeline), to be plotted on the right side
#' @param name_left Name for the left strata of the plot (e.g. resolution used); needs to be a character string
#' @param name_right Name for the right strata of the plot (e.g. resolution used); needs to be a character string
#' @param prefix_left Optional character string as prefix for left axis (if not used, the function will give a warning!)
#' @param prefix_right Optional character string as prefix for right axis (if not used, the function will give a warning!)
#' @param min_cells Minimum number of cells per connection ( > 0 by default).
#' @return A ggplot object that can be plotted.
#' 
#' @details
#' Please note that names need to be character strings. Colors are chosen the same way as they are in pipeline_seurat.py and should correspond to the colors in the reports.
#' 
#' @examples
#' plot_alluvial(path_clusters_left = "/path/to/seurat/all.seurat.dir/20_0.4_1_wilcox/cluster.dir/cluster_ids.rds", 
#' path_clusters_right =  "/path/to/seurat/all.seurat.dir/20_0.6_1_wilcox/cluster.dir/cluster_ids.rds", 
#' name_left = "clusters_20_0.4_1", name_right = "clusters_20_0.6_1")

plotAlluvial <- function(
              path_clusters_left,
              path_clusters_right,
              name_left,
              name_right,
              prefix_left = NULL,
              prefix_right = NULL,
              min_cells = 0) {
  message("Load cluster assignments ... \n")
  cluster_assignment_left <- readClusterIDs(path_clusters_left)
  if (is.null(prefix_left)){
    colnames(cluster_assignment_left) <- c(name_left, "barcode")
  } else {
    cluster_assignment_left[,name_left] <- paste(prefix_left, cluster_assignment_left$cluster_assignment, sep="_")
    cluster_assignment_left$cluster_assignment <- NULL
    colnames(cluster_assignment_left) <- c("barcode", name_left)
  }
  message(paste0("Number of cells in left cluster assignments: ", nrow(cluster_assignment_left)))
  cluster_assignment_right <- readClusterIDs(path_clusters_right)
  if (is.null(prefix_right)){
    colnames(cluster_assignment_right) <- c(name_right, "barcode")
  } else {
    cluster_assignment_right[,name_left] <- paste(prefix_right, cluster_assignment_right$cluster_assignment, sep="_")
    cluster_assignment_right$cluster_assignment <- NULL
    colnames(cluster_assignment_right) <- c("barcode", name_right)
  }
  message(paste0("Number of cells in left cluster assignments: ", nrow(cluster_assignment_right)))
  
  message("Merge datasets ... \n")
  merged <- dplyr::inner_join(cluster_assignment_left, cluster_assignment_right, by="barcode")
  # using the short format (instead of long)
  merged_links <- merged %>% group_by_(name_left, name_right) %>% summarise(value = n())

  message("Check if data is in alluvia format ... \n")
  is_alluvia_form(as.data.frame(merged_links), axes = 1:3, silent = TRUE)

  n_clusters = length(unique(merged[,name_left]))
  colors_use = gg_color_hue(n_clusters)
  
  message("Generate plot ... \n")
  gp <- ggplot(merged_links[merged_links$value > min_cells,],
               aes_string(y = "value", axis1 = name_left, axis2 = name_right)) 
  gp <- gp + geom_alluvium(aes_string(fill = name_left), width = 1/12) 
  gp <- gp + scale_x_discrete(limits = c(name_left, name_right), expand = c(.05, .05))
  gp <- gp + geom_stratum(width = 1/12) + guides(fill = FALSE) 
  gp <- gp + scale_fill_manual(values = colors_use)
  gp <- gp + ylab("Number of cells") + geom_text(stat = "stratum", label.strata = TRUE, size=3) 
  gp <- gp + ggtitle(paste0("Connections with > ", min_cells, " are shown."))
  
  return(gp)
}


#' A helper function to read in cluster_ids.rds files for alluvial plots
#' @param path A rds file with cluster assignments for each cell (as generated by seurat pipeline)
#' @details
#' Helper function for alluvial diagrams to read in cluster assignments from cluster_ids.rds.

readClusterIDs <- function(path) {
  cluster_assignment <- readRDS(path)
  cluster_assignment <- as.data.frame(cluster_assignment)
  cluster_assignment$barcode <- rownames(cluster_assignment)
  return(cluster_assignment)
}


